---
- name: Configure all indexers behavior
  include_tasks: configure_server.yml
- name: Configure each index
  include_tasks: configure_indexes.yml
  loop: "{{ splunk.smartstore }}"
  loop_control:
    loop_var: index