---
- name: Run default Splunk provisioning
  hosts: localhost
  gather_facts: true
  strategy: free
  environment: "{{ ansible_environment | default({}) }}"
  tasks:
  - name: Get existing HEC token
    splunk_api:
      url: "/services/data/inputs/http/splunk_hec_token?output_mode=json"
      method: GET
      user: "{{ splunk.admin_user }}"
      password: "{{ splunk.password }}"
      status_code: [200, 404]
    register: hec_token
    when: ('hec' in splunk and 'token' in splunk.hec) or ('hec_token' in splunk)
    no_log: "{{ hide_password }}"