---
- name: "Restart the splunkd service - Via CLI"
  command: "{{ splunk.exec }} restart --answer-yes --accept-license"
  become: yes
  become_user: "{{ splunk.user }}"
  register: task_result
  until: task_result.rc == 0
  retries: "{{ retry_num }}"
  delay: "{{ restart_retry_delay }}"
  when: not splunk.enable_service

- name: "Restart the splunkd service - Via Linux systemd or init"
  service:
    name: "{{ splunk_service_name }}"
    state: restarted
  when: splunk.enable_service and ansible_system is match("Linux")
  become: yes
  become_user: "{{ privileged_user }}"

- name: "Restart the splunkd service - Via windows system"
  win_service:
    name: "{{ splunk_service_name }}"
    state: restarted
  when: splunk.enable_service and not ansible_system is match("Linux")

- name: Check if UDS file exists
  stat:
    path: "/opt/splunkforwarder/var/run/splunk/cli.socket"
  register: socket_file

- name: "Wait for splunkd management port"
  wait_for:
    port: "{{ splunk.svc_port }}"
  when: not socket_file.stat.exists or (socket_file.stat.exists and socket_file.stat.size == 0)
