---
- name: Run ESS post-install setup
  command: "{{ splunk.exec }} search '| essinstall' -auth {{ splunk.admin_user }}:{{ splunk.password }}"
  no_log: "{{ hide_password }}"
  become: yes
  become_user: "{{ splunk.user }}"
  register: essinstall
  changed_when: essinstall.rc == 0
  failed_when: essinstall.rc != 0
  retries: 3
  async: 900
  poll: 20
  notify:
    - Restart the splunkd service
