- name: Create ITSI admin role
  splunk_api:
    url: "/servicesNS/nobody/itsi/authorization/roles/"
    method: "POST"
    cert_prefix: "{{ cert_prefix }}"
    username: "{{ splunk.admin_user }}"
    password: "{{ splunk.password }}"
    svc_port: "{{ splunk.svc_port }}"
    body: 
      name: "itsi_admin"
      imported_roles: ["itoa_user", "itoa_analyst", "itoa_admin"]
    body_format: "form-urlencoded"
    status_code: [201, 409]
  register: setup_itsi_role
  ignore_errors: yes
  delay: "{{ retry_delay }}"
  retries: "{{ retry_num }}"
  until: setup_itsi_role.status in [201, 409]
  changed_when: setup_itsi_role.status == 201
  no_log: "{{ hide_password }}"
  notify:
    - Restart the splunkd service

- name: Create ITSI admin user
  splunk_api:
    url: "/servicesNS/nobody/itsi/authentication/users/admin"
    method: "POST"
    cert_prefix: "{{ cert_prefix }}"
    username: "{{ splunk.admin_user }}"
    password: "{{ splunk.password }}"
    svc_port: "{{ splunk.svc_port }}"
    body:
      roles: ["itsi_admin", "admin"]
    body_format: "form-urlencoded"
    status_code: [200, 409]
  register: setup_itsi_user
  retries: "{{ retry_num }}"
  delay: "{{ retry_delay }}"
  until: setup_itsi_user.status in [200, 409]
  changed_when: setup_itsi_user.status == 200
  no_log: "{{ hide_password }}"
  notify:
    - Restart the splunkd service

