---
- name: Grab spark master service IP
  command: "hostname -i"
  register: spark_master_ip

- name: Create spark-env.sh
  copy:
    dest: "{{ splunk.dfs.spark_home }}/conf/spark-env.sh"
    content: |
      export SPARK_MASTER_WEBUI_PORT={{ splunk.dfs.spark_master_webui_port }}
      export SPARK_MASTER_PORT={{ splunk.dfs.port }}
      export SPARK_DAEMON_MEMORY=2g
      export SPARK_PID_DIR={{ splunk.dfs.dfs_home }}
      export SPARK_HOME={{ splunk.dfs.spark_home }}
      export SPARK_MASTER_HOST={{ spark_master_ip.stdout }}
  become_user: "{{ privileged_user }}"
  become: yes

- name: Create spark-defaults.conf
  become: yes
  become_user: "{{ privileged_user }}"
  blockinfile:
    path: "{{ splunk.dfs.spark_home }}/conf/spark-defaults.conf"
    create: yes
    mode: u+rw
    insertafter: EOF
    marker: ""
    block: |
      spark.eventLog.dir file://{{ splunk.dfs.dfs_home }}/eventlog
      spark.history.fs.logDirectory file://{{ splunk.dfs.dfs_home }}/eventlog
