---
- name: Check for required restarts
  splunk_api:
    method: GET
    endpoint: /services/messages/restart_required?output_mode=json
    username: "{{ splunk.admin_user }}"
    password: "{{ splunk.password }}"
    cert_prefix: "{{ cert_prefix }}"
    validate_certs: false
    status_code: "200,404"
    timeout: 10
    notify:
      - Restart the splunkd service
  register: restart_required
  changed_when: restart_required.content
  until: restart_required.content
  retries: 5
  delay: "{{ retry_delay }}"
  no_log: "{{ hide_password }}"
