---
- name: Check if UDS file exists
  stat:
    path: "{{ splunk.home }}"/var/run/splunk/cli.socket
  register: client_socket_file

- name: Check if listening on 8089
  shell: "netstat -plnt"
  register: port_status
  when: not client_socket_file.stat.exists

- name: Display UF is using UDS
  debug:
    msg: "UF (s) are using UDS"
    when client_socket_file.stat.exists || (port_status.length > 0 and port_status.find("8089") != -1)

- name: Display UF is using TCP
  debug:
    msg: "UF (s) are using TCP"
    when not client_socket_file.stat.exists || port_status.length == 0 || (port_status.length > 0 and port_status.find("8089") == -1)
