---
- name: Configure to set Mgmt Mode as auto (Allows UDS)
  ini_file:
    dest: "{{ splunk.home }}/etc/system/local/server.conf"
    option: "mgmtMode"
    section: "httpServer"
    value: "auto"
    owner: "{{ splunk.user }}"
    group: "{{ splunk.group }}"

- name: Configure to set Mgmt Mode as tcp (Allows only TCP)
  ini_file:
    dest: "{{ splunk.home }}/etc/system/local/server.conf"
    option: "mgmtMode"
    section: "httpServer"
    value: "tcp"
    owner: "{{ splunk.user }}"
    group: "{{ splunk.group }}"
