---
- name: GET OptInVersion
  splunk_api:
    method: GET
    url: "/servicesNS/nobody/splunk_instrumentation/admin/telemetry/general?output_mode=json"
    username: "{{ splunk.admin_user }}"
    password: "{{ splunk.password }}"
    svc_port: "{{ splunk.svc_port }}"
    validate_certs: false
     status_code: [200]
    timeout: 10
    return_content: yes
  register: telemetry
  no_log: "{{ hide_password }}"

- name: Disable Popups
  splunk_api:
    method: POST
    url: "{{ item.key }}"
    username: "{{ splunk.admin_user }}"
    password: "{{ splunk.password }}"
    svc_port: "{{ splunk.svc_port }}"
    body: "{{ item.value }}"
    validate_certs: false
    status_code: 200,201,409
  with_items:
    - { key: "/servicesNS/admin/user-prefs/data/user-prefs/general", value: "hideInstrumentationOptInModal=1&notification_python_3_impact=false&showWhatsNew=0" }
    - { key: "/servicesNS/nobody/splunk_instrumentation/admin/telemetry/general", value: "showOptInModal=0&optInVersionAcknowledged={{ telemetry['json']['entry'][0]['content']['optInVersion'] }}" }
    - { key: "/servicesNS/admin/search/data/ui/ui-tour/search-tour", value: "tourPage=search&viewed=1" }
