---
# splunk.s2s_enableSSL, splunk.s2s_enableSSL_cert, and splunk.s2s_enableSSL_password
# should be defined already given the check in enable_s2s.yml

- name: Enable S2S SSL
  ini_file:
    dest: "{{ splunk.home }}/etc/system/local/inputs.conf"
    section: "splunktcp-ssl:{{ splunk.s2s_port }}"
    option: "disabled"
    value: "0"
  notify:
    - Restart the splunkd service

- name: Set S2S SSL certificate path
  ini_file:
    dest: "{{ splunk.home }}/etc/system/local/inputs.conf"
    section: SSL
    option: serverCert
    value: "{{ splunk.s2s_enableSSL_cert }}"
  notify:
    - Restart the splunkd service

- name: Set S2S SSL certificate password
  ini_file:
    dest: "{{ splunk.home }}/etc/system/local/inputs.conf"
    section: SSL
    option: sslPassword
    value: "{{ splunk.s2s_enableSSL_password }}"
  notify:
    - Restart the splunkd service

# If splunk.s2s_enableSSL_ca is not defined, it will default to
# $SPLUNK_HOME/etc/auth/ca.pem
- name: Set S2S SSL root ca
  ini_file:
    dest: "{{ splunk.home }}/etc/system/local/server.conf"
    section: sslConfig
    option: sslRootCAPath
    value: "{{ splunk.s2s_enableSSL_ca }}"
  when:
    - '"s2s_enableSSL_ca" in splunk'
    - splunk.s2s_enableSSL_ca
  notify:
    - Restart the splunkd service
