---
# Forwarding traffic to Data Stream Processor: https://docs.splunk.com/Documentation/DSP/latest/Data/Forwarder
- name: Fetch DigiCert CA
  get_url:
    url: https://cacerts.digicert.com/DigiCertGlobalRootCA.crt.pem
    dest: "{{ splunk.home }}/etc/auth/DigiCertGlobalRootCA.pem"
    owner: "{{ splunk.user }}"
    group: "{{ splunk.group }}"

- name: Set root CA
  ini_file:
    path: "{{ splunk.home }}/etc/system/local/server.conf"
    section: sslConfig
    option: sslRootCAPath
    value: "{{ splunk.home }}/etc/auth/DigiCertGlobalRootCA.pem"
    owner: "{{ splunk.user }}"
    group: "{{ splunk.group }}"
  register: dsp_ca

- name: Configure DSP output
  ini_file:
    path: "{{ splunk.home }}/etc/system/local/outputs.conf"
    section: "tcpout:datastreamprocessor"
    option: "{{ item.key }}"
    value: "{{ item.value }}"
    owner: "{{ splunk.user }}"
    group: "{{ splunk.group }}"
  with_items:
    - {key: "server", value: "{{ splunk.dsp.server }}"}
    - {key: "clientCert", value: "{{ splunk.dsp.cert }}"}
    - {key: "sslVerifyServerCert", value: "{{ splunk.s2s.verify | default('false') }}"}
  when:
    - splunk.dsp.server is defined and splunk.dsp.server
    - splunk.dsp.cert is defined and splunk.dsp.cert
  register: dsp_group

- name: "Get Splunk status"
  command: "{{ splunk.exec }} status --accept-license --answer-yes --no-prompt"
  become: yes
  become_user: "{{ splunk.user }}"
  register: splunk_status
  changed_when: False
  failed_when: False
  ignore_errors: yes

# We want to restart only when Splunk is currently running and when any of the above have changed
- name: Trigger restart
  command: ls
  changed_when: splunk_status.rc == 0 and (dsp_ca is changed or dsp_group is changed)
  notify:
    - Restart the splunkd service
