---
- include_tasks: enable_s2s_ssl.yml
  when:
    - "'s2s_enableSSL' in splunk"
    - splunk.s2s_enableSSL | bool
    - '"s2s_enableSSL_cert" in splunk'
    - splunk.s2s_enableSSL_cert
    - '"s2s_enableSSL_password" in splunk'
    - splunk.s2s_enableSSL_password

- name: Enable Splunk-to-Splunk port
  command: "{{ splunk.exec }} enable listen {{ splunk.s2s_port }} -auth {{ splunk.admin_user }}:{{ splunk.password }} --accept-license --answer-yes --no-prompt"
  become: yes
  become_user: "{{ splunk.user }}"
  when:
    - "'s2s_enableSSL' in splunk"
    - not splunk.s2s_enableSSL | bool
  register: enable_s2s_status
  changed_when: enable_s2s_status.rc == 0 and 'already exists' not in enable_s2s_status.stdout
  failed_when:
    - enable_s2s_status.rc !=0
    - "'already exists' not in enable_s2s_status.stderr"
  no_log: "{{ hide_password }}"
