---
# Choose privileged username for current OS
- name: "Set privilege escalation user"
  set_fact:
    privileged_user: "{% if ansible_system is match('CYGWIN*|Win32NT') %}Administrator{% else %}root{% endif %}"

# If there is no Splunk executable, we will need to install.
- name: "Check for existing installation"
  stat:
    path: "{{ splunk.exec }}"
  become: yes
  become_user: "{{ privileged_user }}"
  register: pre_existing_splunk_exec

- name: "Set splunk install fact"
  set_fact:
    splunk_install: "{{ not pre_existing_splunk_exec.stat.exists | default(True) }}"

# We know if this is the first time we are executing Splunk by checking if a splunk.secret file exists.
# Since running the software will generate this and we assume nobody will delete the splunk.secret.
- name: "Check for existing splunk secret"
  stat:
    path: "{{ splunk.home }}/etc/auth/splunk.secret"
  register: pre_existing_splunk_secret
  become: yes
  become_user: "{{ privileged_user }}"

- name: "Set first run fact"
  set_fact:
    first_run: "{{ not pre_existing_splunk_secret.stat.exists | default(True) }}"

# Checking that the .dockerenv file exists is enough to know if we are inside a docker container.
- name: "Check if we are in a docker"
  stat:
    path: "/.dockerenv"
  register: docker_env

- name: "Set docker fact"
  set_fact:
    is_docker: "{{ docker_env.stat.exists | default(False) }}"

- name: "Set splunk_build_type fact"
  include_tasks: get_facts_build_type.yml

- name: "Set target version fact"
  include_tasks: get_facts_target_version.yml
  when: splunk_target_version is not defined or splunk_target_version == none

# We can apply the same logic to the current version by checking which manifest file is in Splunk
- name: "Find manifests"
  find:
    paths: "{{ splunk.home }}"
    patterns: ".*-manifest$"
    use_regex: yes
  become: yes
  become_user: "{{ privileged_user }}"
  register: manifests

- name: "Set current version fact"
  set_fact:
    splunk_current_version: "{{ manifests.files[0].path | regex_search(regexp, '\\1') if (manifests.matched == 1) else '0' }}"
  vars:
    regexp: 'splunk\D*?-((\d+)\.(\d+)\.(\d+))'

# We are upgrading if it is not a fresh installation and the current version is different from the target version
- name: "Setting upgrade fact"
  set_fact:
    splunk_upgrade: "{{ 'build_location' in splunk and splunk.build_location and not splunk_install and splunk_target_version and splunk_target_version != splunk_current_version | default(False) }}"
