---
- name: Define versioned file name
  set_fact:
    versioned_name: "spark-{ splunk.dfs.spark_version }}-bin-hadoop{{ splunk.dfs.hadoop_version }}"

- name: Download Hadoop
  include_tasks: s3_download.yml
  vars:
    file_name: "{{ versioned_name }}.tgz"

- name: Untar Spark
  unarchive:
    src: "/tmp/{{ versioned_name }}.tgz"
    dest: "/tmp/"
    copy: no

- name: Create Spark directory
  file:
    path: "{{ splunk.dfs.spark_home }}"
    mode: 0777
    state: directory
  become_user: "{{ privileged_user }}"
  become: yes

- name: Move Spark package to directory
  shell: /bin/bash -c "mv /tmp/{{ versioned_name }}/* {{ splunk.dfs.spark_home }}"

- name: Chmod Spark directory
  file:
    path: "{{ splunk.dfs.spark_home }}"
    state: directory
    owner: "{{ splunk.user }}"
    group: "{{ splunk.group }}"
    recurse: yes