- name: Install Splunk (Linux)
  unarchive:
    src: "{{ splunk.build_location }}"
    dest: "{{ splunk.opt }}"
    owner: "{{ splunk.user }}"
    group: "{{ splunk.group }}"
    remote_src: "{{ splunk.build_remote_src }}"
  register: install_result
  until: install_result is succeeded
  retries: "{{ retry_num }}"
  delay: 3
  become: yes
  become_user: "{{ privileged_user }}"

