---
- name: Check if requests_unixsocket exists
  command: "pip list | grep 'requests-unixsocket'"
  register: requests_unixsocket_check
  ignore_errors: true

- name: Install and upgrade pip
  pip:
    name: pip
    extra_args: --upgrade
    executable: pip3
  when: requests_unixsocket_check is failed

- name: Check if pip3 unixsocket exits
  command: "pip3 list | grep 'requests-unixsocket'"
  register: requests_unixsocket_check_py3
  when: requests_unixsocket_check is failed
  ignore_errors: true

- name: Install missing requests_unixsocket
  ansible.builtin.pip:
    name: "requests_unixsocket"
