---
- name: Set Mgmt Mode
  ini_file:
    dest: "{{ splunk.home }}/etc/system/local/server.conf"
    option: "mgmtMode"
    section: "httpServer"
    value: "tcp"
    owner: "{{ splunk.user }}"
    group: "{{ splunk.group }}"

