---
- name: Set HTTP Port
  ini_file:
    dest: "{{ splunk.home }}/etc/system/local/web.conf"
    section: settings
    option: "httpport"
    value: "{{ splunk.http_port }}"
    owner: "{{ splunk.user }}"
    group: "{{ splunk.group }}"

- name: Set API port
  ini_file:
    dest: "{{ splunk.home }}/etc/system/local/web.conf"
    section: settings
    option: "mgmtHostPort"
    value: "{{ splunk.svc_port }}"
    owner: "{{ splunk.user }}"
    group: "{{ splunk.group }}"
