---
- name: Wait for Splunk process to be running
  wait_for:
    path: "{{ splunk.pid }}"
    state: present
  when: ansible_system is match("Linux")

- name: Check if UDS file exists
  stat:
    path: "/opt/splunkforwarder/var/run/splunk/cli.socket"
  register: socket_file

- name: Wait for the Splunk service port to be available
  wait_for:
    host: 127.0.0.1
    port: "{{ splunk.svc_port }}"
    timeout: 180
  when: not socket_file.stat.exists or (socket_file.stat.exists and socket_file.stat.size == 0)
