---
- name: Download spark
  include_tasks: roles/splunk_common/tasks/s3_download.yml
  vars:
    file_name: "spark-{{ splunk.dfs.spark_version }}-bin-hadoop{{ splunk.dfs.hadoop_version }}.tgz"

- name: Get spark dir listing
  find:
    paths: "{{ splunk.dfs.spark_home }}"
  register: spark_listing

- name: Print listing
  debug:
    msg: "{{ spark_listing }}"

- name: Create spark directory
  file:
    path: "{{ splunk.dfs.spark_home }}"
    mode: 0777
    state: directory
  become_user: root
  become: yes

- name: Untar Spark tarfile into the Spark Home directory
  unarchive:
    src: "/tmp/spark-{{ splunk.dfs.spark_version }}-bin-hadoop{{ splunk.dfs.hadoop_version }}.tgz"
    dest: "{{ splunk.dfs.spark_home }}"
    copy: no