---
- name: Download OpenJDK
  include_tasks: roles/splunk_common/tasks/s3_download.yml
  vars:
    file_name: "{{ openjdk.version }}_{{ openjdk.platform }}_{{ openjdk.build }}.tar.gz"

- name: Create directory to unpack Oracle JRE
  file:
    path: "{{ openjdk.jre_base_dir }}"
    state: directory
    owner: ansible
    group: ansible
  become_user: root
  become: yes

- name: Untar OpenJDK tarfile
  unarchive:
    src: "/tmp/{{ openjdk.version }}_{{ openjdk.platform }}_{{ openjdk.build }}.tar.gz"
    dest: "{{ openjdk.jre_base_dir }}"
    copy: no
    owner: ansible
    group: ansible
  become_user: root
  become: yes

- name: Create alternatives for installed JRE
  shell: "update-alternatives --install /usr/bin/java java {{ openjdk.jre_base_dir }}/{{ openjdk.jre_dir }}/bin/java 100"
  become_user: root
  become: yes

- name: Set Java version
  shell: "update-alternatives --set java {{ openjdk.jre_base_dir }}/{{ openjdk.jre_dir }}/bin/java"
  become_user: root
  become: yes